### ISSUE TITLE
GPU branch requires CUDA, even in CPU mode

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#106]
Cannot compile GPU branch in CPU mode without CUDA, nvhpc, etc. This will have to be fixed, since it will soon be the `master` branch and must be compatible for most folks, including CPU-only users. Fix might include using `fypp` or macros.

**Comment by henryleberre** [comment]
One way to fix this would be to define a preprocessor variable when compiling that can instruct the code whether or not to include portions that would require a different compiler configuration/mode. These could be:
- `-DCPU_MODE`
- `-DGPU_MODE`
It would be a trivial change to `mfc.user.yaml`.

**Comment by sbryngelson** [comment]
I think we would also need to change the `makefile`s? because part of the problem is trying to compile `nvtx.f90` without cuda.

**Comment by henryleberre** [comment]
The entire nvtx module could be wrapped in:
```fortran
#ifdef GPU_MODE
module nvtx 
...
#endif // #ifdef GPU_MODE
```

**Comment by sbryngelson** [comment]
interesting trick. though the makefile would still try to compile the empty file. not sure that would work. would need to be a little more slick
