### ISSUE TITLE
Issue building HDF5 (and possibly other) packages

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#131]
**Describe the bug**
HDF5 does not build due to a git checkout error seemingly.

**To Reproduce**
Happens on my M1 Macbook. Building using GPU branch of `MFC-develop` and `release-cpu`. Error is:

```
> > > Package silo requires hdf5.
> > > > Package hdf5:
> > > > > Checking out 4aa40365623cf35643b262781f92578220c42bbb...

FATAL ERROR> Failed to execute command "cd "/Users/spencer/Downloads/MFC-develop/build/common/src/hdf5" && git checkout
"4aa40365623cf35643b262781f92578220c42bbb" >> "/Users/spencer/Downloads/MFC-develop/build/common/log/hdf5.log" 2>&1".
We apologize for the inconvenience. If you believe this is an issue with MFC, please visit
https://github.com/MFlowCode/MFC-develop/issues to file an issue.
```

which fails with 

```
Cloning into '/Users/spencer/Downloads/MFC-develop/build/common/src/hdf5'...
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

error: The following untracked working tree files would be overwritten by checkout:
```

**Comment by sbryngelson** [comment]
I believe the fix is to change this line in `build.py` 

```
./build.py:                    f'cd "{self.get_source_path(name)}" && git checkout "{conf.fetch.params.hash}" >> "{logfile.name}" 2>&1')
```
to use `git checkout -f ` according to this link https://stackoverflow.com/questions/4858047/gitignore-and-the-following-untracked-working-tree-files-would-be-overwritten

**Comment by henryleberre** [comment]
@sbryngelson This is no longer an issue on my fork [henryleberre/MFC](https://github.com/henryleberre/MFC) as we now use CMake to fetch & build dependencies. @anandrdbz should soon be done adding the final GPU tests. I had to file a compiler bug report with NVHPC 22.5. I will now check whether the fork works on all the computers I have access to in CPU mode. If it does, then we might consider merging. Or if you prefer, I can push a fix for this particular issue.
