### ISSUE TITLE
CI with GPU runner

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#16]
Add GPU CI support via Google Cloud Build runners: https://cloud.google.com/build
* Looks like this should be free so long as we don't use more than 120 build-minutes/day (which I suspect we will never exceed):

```
FEATURE | PRICING (USD)
First 120 build-minutes per day | Free
Additional build-minutes | $0.003 per minute
```

* Looks like this should be straightforward if we have a docker container: https://cloud.google.com/community/tutorials/cicd-cloud-run-github-actions

We could also consider other cloud-based runners if they are free (or near-free).

**Comment by sbryngelson** [comment]
FYI: Just found this:

> GitHub Actions usage is free for both public repositories and self-hosted runners. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits.

From [here](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions). So all supported actions are free for us since the repos are public.

**Comment by sbryngelson** [comment]
More info: https://on-demand.gputechconf.com/gtc/2018/presentation/s8563-building-a-gpu-focused-ci-solution.pdf

**Comment by aktech** [comment]
Hi @sbryngelson  I am the creator of Cirun.io, "GPU runner" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

https://github.com/pystatgen/sgkit/
https://github.com/qutip/qutip-cupy
https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/blob/master/.cirun.yml

It is fairly simple to setup, all you need is a cloud account (like say AWS) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)

**Comment by sbryngelson** [comment]
@henryleberre what's partially needed here is an actual GPU runner, otherwise it will just not really test the OpenACC code generation.

**Comment by henryleberre** [comment]
@sbryngelson Indeed. The idea behind this implementation was to at least compile and run it using NVHPC, despite testing on CPUs, before we figure out how to run it on actual hardware.

**Comment by sbryngelson** [comment]
Update: @henryleberre has this working on OLCF Gitlab via Ascent CI for GPUs. Some other features are needed before this can be merged into GPU/master branches here.
