### ISSUE TITLE
Can SECRETS be used for CI on remote clusters

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#41]
Can we use ssh keys in repository secrets to build a CI pipeline on a remote server like Bridges/Expanse? If so, the workflow might look like

* Ubuntu login
* Pass SSH secret to log into XSEDE
* Submit batch script
* Wait until completion
* Check if passed
* Abort

**Comment by henryleberre** [comment]
This seems to be possible with this pre-written GitHub action:

https://github.com/appleboy/ssh-action

The only issue is that my account is protected with Duo for 2FA. I was looking at XSEDE's documentation and couldn't find if they supported keys for signing in. So this would require credentials to a XSEDE account not protected by 2FA. We could even create one specifically for CI.

**Comment by sbryngelson** [comment]
Very nice. XSEDE does not require 2FA (my account doesn't use it). I password-less login to both Expanse and Bridges2. 2FA rules out Summit (though we will hopefully be approved to use Ascent for CI soon). We need to be on GT VPN for Phoenix, so that is probably out of the question.

**Comment by henryleberre** [comment]
How did you set up your password-less authentication? We could technically make Phoenix work with more credentials for the VPN but it's probably unnecessary considering we could make it work with Expanse or Bridges2.

**Comment by sbryngelson** [comment]
Just the usual process of adding my private ssh key to my Bridges2/Expanse `.ssh/known_hosts` or whatever (I think). I didn't do anything fancy.

**Comment by henryleberre** [comment]
Great. I'm glad it works that way!

**Comment by sbryngelson** [comment]
Closing as this is not a real issue for now.
