### ISSUE TITLE
Clean up git history to speed up `git clone`

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#46]
Some recent pushes (cough https://github.com/MFlowCode/MFC-develop/commit/d655b7388b2fbf723444eee16fbd515c5e144bc7 cough) introduced a ton of files into the git history. Even though they are deleted now, they still live in history and cause `git clone` to be slow. It seems like this can be fixed via [something like this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) or [here](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository)

**Comment by sbryngelson** [comment]
I am closing this issue as I suspect it will be cured when we move to the main `MFC` repo.

**Comment by henryleberre** [comment]
Good news, commit d655b7388b2fbf723444eee16fbd515c5e144bc7 (aka *strip out some doxygen info*) appears to only be present in the [phasechange](https://github.com/MFlowCode/MFC-develop/compare/phasechange) and [stale-master](https://github.com/MFlowCode/MFC-develop/compare/stale-master) branches. Merging from the GPU branch had the unintentional benefit of not inheriting from this commit.

The commit doesn't show up in:
- `git log | grep -i 'strip out'`
- `git log | grep -i 'doxygen'`
- `git rev-list --all | grep -i 'd655b7388b2fbf723444eee16fbd515c5e144bc7'`
