### ISSUE TITLE
MacOS uses old Bash -- incompatible `declare` command

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#48]
The default bash on MacOS is very old: 
``` /Users/spencer $ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
```

This has an incompatibility with the `declare` command in `_install.sh` because the flag `declare -A` is not supported:

```
 /Users/spencer $ declare -A
bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

I'm not sure if the `-A` is really important or not.

**Comment by sbryngelson** [comment]
Note that the default `zsh` works fine for this, but some people will probably still be using the bundled `bash`.

**Comment by henryleberre** [comment]
The Bash 3 alternatives don't look great. We need the `-A` to declare a dictionary of sorts. I use it to store which alternative we use for different command line utilities (like wget/curl). 

Could we just detect whether `declare -A` works, and throw an understandable error if it fails?
