### ISSUE TITLE
Hypoelasticity memory leak

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#6]
From @js-spratt 
> I’m running into a similar ‘out of memory error’ with the CPU code on Expanse currently. This occurs after ~1850 time-steps of the simulation, when running a simulation with 8 million grid points on 4 expanse nodes (128 cores/node, 248G memory/node). I’ll see if using the flags you suggested above solve the issue. This is the hypoelastic code, so outputting 14 variables in this particular simulation (in 3D)

**Comment by js-spratt** [comment]
Update: the memory leak has been fixed, but the 3D hypoelastic code encounters another error occurring in variable deallocation (at final time only, so a more minor issue). I'll push changes to the hypoelastic branch once that's fixed.

**Comment by sbryngelson** [comment]
@js-spratt update on this?
