### ISSUE TITLE
`fypp` preprocessing magic for GPU directional splitting

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#74]
Apply to Riemann solvers then move to other macros (buffer size?).

**Comment by henryleberre** [comment]
Introduced with @anandrdbz's help in:
- 5407e362e50e99e09a6c48b111e48bd0cd7152ec
- 30c1973caf2b3cf60ee509b8f19adff7c0094b68
- d6fa197d60c5e91315b5bfa3bafc90e73138106a

Once I ensure Fypp works nicely with the build system, I will submit a pull request.

**Comment by sbryngelson** [comment]
looks magical!

**Comment by henryleberre** [comment]
@sbryngelson Should this issue be closed or are there other areas of the code I should add `fypp` to?

**Comment by sbryngelson** [comment]
This issue is closed for now. `fypp` may continue to be used for future enhancements. @henryleberre it would be nice to have a paragraph in the `readme.md` that mentions that we use `fypp` for certain things and in certain places.
