### ISSUE TITLE
Support for different queue systems in `input.py` and the master script

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#75]
Per title. Add support for different queue systems: PBS, SLURM, and the Oak Ridge system should cover almost everything. Will need to add some inputs to the `input.py`.

**Comment by henryleberre** [comment]
Would you wish having something akin to `./mfc.sh --run` ?

If so, we should decide whether we want the desired run's configuration to be specified in `mfc.conf.yaml` or through arguments to the script. I'm not exactly sure what file you would give it as an argument (e.g a `.inp` or `.py` that generates the case).

**Comment by sbryngelson** [comment]
you would put it in `input.py` if I'm not mistaken

**Comment by sbryngelson** [comment]
Just dumping this from the Slack discussion for posterity.

Spencer: this will be useful for you later @henryleberre `https://slurm.schedmd.com/rosetta.pdf`. We will want to support PBS, Slurm, and LSF simultaneously.  The last two are irrelevant.

You should be able to auto-detect what scheduler a supercomputer uses, you could check for the existence of several of the commands. e.g.
```
if (qsub + qdel + qstat all exist) then: scheduler=PBS;
elif (sbatch + scancel + squeue all exist) then: scheduler=SLURM;
elif (bsub + bkill + bjobs all exist) then: scheduler=LSF;
```

I recommend checking if multiple of these commands exists because sometimes people alias one to the other either on their own or the cluster manager does it for them. Once you know what scheduler you have you can just patch the `input.py` variables into an auto-generated batch script for that type of scheduler. Right now you have to go into `m_python_proxy.py` and comment/uncomment lines yourself if you want to change the scheduler
