### ISSUE TITLE
Create directory `D` if it's needed but doesn't exist

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#84]
Sometimes we need the directory `D/` to put serial output files or probe output files. In the `1d_bubblescreen` problem in `samples` on the master branch, running this case gives the immediate error 

```
samples/1D_bubblescreen $ python3 input.py simulation
dt:  0.013648856933996752

simulation>> Preparing serial job ...


simulation>> Serial job in progress ...

 Read input file
 Broadcast
 R0 weights:    1.0000000000000000
 R0 abscissas:    1.0000000000000000
 Initialize
At line 349 of file m_data_output.f90 (unit = 31)
Fortran runtime error: Cannot open file './D/probe1_prim.dat': No such file or directory
```

because the directory `D` does not exist. There is a way to create that directory if it doesn't exist from within Fortran: https://www.google.com/search?q=create+directory+if+it+doesn%27t+exist+fortran

**Comment by henryleberre** [comment]
I've looked around and I'm amazed that even newer Fortran standards don't specify how `INQUIRE` should handle directories.
I think that the most portable solution that relies less heavily on compiler-specific implementation would to create a very simple C++ static library that exports a single function that checks whether a directory exists. It would then be linked to Fortran. C++17's `std::filesystem::exists` makes this a one-liner.
If you'd prefer a hackier but simpler approach, we could just call `system` and `mkdir` but it's technically not guarantied to always work - though it probably would.
Which do you prefer @sbryngelson ?

**Comment by henryleberre** [comment]
Or, alternatively, we could just create it in Python when running MFC.

**Comment by sbryngelson** [comment]
It's easy to do in Fortran

**Comment by sbryngelson** [comment]
@henryleberre there are other parts of MFC that test if a directory exists. (this has to be the case, because you can start with an empty directory and run MFC and it will create and populate them). So just do whatever is already done in Fortran.

**Comment by sbryngelson** [comment]
@henryleberre check this out https://github.com/MFlowCode/MFC-develop/blob/d47c647a75db3f9ed7a5eb6946b3e931b20907aa/src/post_process_code/m_data_output.f90#L267-L288
