### ISSUE TITLE
Investigate static linking of (most if not all) libraries

### ISSUE THREAD

**Issue by henryleberre** [MFlowCode/MFC-develop#90]
Recent issues on the Richardson cluster with regards to building and runtime linking of `libgfortran` require us to think about linking most libraries statically as not to have to worry about `LD_LIBRARY_PATH` and conflicting versions of standard runtime libraries on nodes, especially while submitting jobs. 

As per @sbryngelson's comments, we should check compatibility of flags required for static linking with:
- Different compilers
- Different versions

(especially `-static-libgfortran`)

**Comment by henryleberre** [comment]
I chose to link MFC's dependencies statically so that there would be no runtime resolving of shared libraries by the system's dynamic loader. Thus, executing MFC no longer requires prepending `build/common/build/lib` to the user's `$LD_LIBRARY_PATH`. Hopefully, this will prevent related issues in the future.
There is no standard way to statically link to Fortran's standard library. (Although it's easy with `gfortran`). Fortunately, I don't think it is necessary, at least for now.
- PGI: `-Bstatic_pgi` ([ref](https://docs.nvidia.com/hpc-sdk/pgi-compilers/20.1/x86/pgi-ref-guide/index.htm))
- GNU: `-static-libgfortran` ([ref](https://gcc.gnu.org/onlinedocs/gfortran/Link-Options.html))

**Comment by sbryngelson** [comment]
Sounds good. Will close with the pull request.
