### ISSUE TITLE
Is `-fignore-rank-mismatch` still relevant?

### ISSUE THREAD

**Issue by sbryngelson** [MFlowCode/MFC-develop#96]
At some point there was a push to either master branch or GPU branch, post_process_code (I think) that got rid of this requirement for GCC>10.0. This seems to be causing a problem again. MFC will not compile master branch with GCC 10+ without this flag.

**Comment by sbryngelson** [comment]
Update - compiled master with gcc10.0.3 and it was fine.

**Comment by henryleberre** [comment]
I've never encountered this issue while compiling with newer GCC versions either. Should this issue be closed?
